#!/usr/bin/env python3
"""
Generate LaTeX tables ready to paste into the paper.
Output: results/tables.tex
"""

import json
import numpy as np

RESULTS_FILE = 'results/benchmark_results.json'
OUT_FILE = 'results/tables.tex'

with open(RESULTS_FILE) as f:
    results = json.load(f)

dims = sorted(set(r['n'] for r in results))
sec_types = sorted(set(r['secret_type'] for r in results))
q = results[0]['q']


def rate(records, key):
    if not records:
        return 0.0
    return sum(r[key] for r in records) / len(records) * 100


def mtime(records, key):
    if not records:
        return 0.0
    return float(np.mean([r[key] for r in records]))


def std_time(records, key):
    if not records:
        return 0.0
    return float(np.std([r[key] for r in records]))


def latex_escape(s):
    return s.replace('_', '\\_')


lines = []
lines.append("% Auto-generated by generate_latex_tables.py")
lines.append("% Do not edit manually.\n")

# ============================================================
# TABLE 1: Success rate by dimension (all methods, ternary secrets)
# ============================================================
lines.append("% === TABLE 1: Success Rate by Dimension (Ternary Secrets) ===")
lines.append("\\begin{table}[t]")
lines.append("\\caption{Success rate (\\%) by dimension for ternary secrets ($q=%d$, $m=2n$, 10 instances each).}" % q)
lines.append("\\label{tab:success-rate-dim}")
lines.append("\\centering")
lines.append("\\small")
lines.append("\\begin{tabular}{cccccc}")
lines.append("\\toprule")
lines.append("$n$ & MILP-HiGHS & MILP-CBC & LLL & BKZ-15 & Winner \\\\")
lines.append("\\midrule")
for n in dims:
    sub = [r for r in results if r['n'] == n and r['secret_type'] == 'ternary']
    h = rate(sub, 'highs_success')
    c = rate(sub, 'cbc_success')
    l = rate(sub, 'lll_success')
    b = rate(sub, 'bkz_success')
    # Determine winner
    rates = {'HiGHS': h, 'CBC': c, 'LLL': l, 'BKZ': b}
    winner = max(rates, key=rates.get)
    if sum(1 for v in rates.values() if abs(v - rates[winner]) < 1.0) > 1:
        winner = 'Tie'
    def fmt(v):
        return f"\\textbf{{{v:.1f}}}" if abs(v - rates[max(rates, key=rates.get)]) < 0.5 else f"{v:.1f}"
    lines.append(f"{n} & {fmt(h)} & {fmt(c)} & {fmt(l)} & {fmt(b)} & {winner} \\\\")
lines.append("\\bottomrule")
lines.append("\\end{tabular}")
lines.append("\\end{table}\n")

# ============================================================
# TABLE 2: HiGHS vs CBC solver comparison
# ============================================================
lines.append("% === TABLE 2: HiGHS vs CBC Solver Comparison ===")
lines.append("\\begin{table}[t]")
lines.append("\\caption{Comparison of open-source MILP solvers HiGHS and CBC across all configurations ($q=%d$, 10 instances each).}" % q)
lines.append("\\label{tab:solver-comparison}")
lines.append("\\centering")
lines.append("\\small")
lines.append("\\begin{tabular}{lcccc}")
lines.append("\\toprule")
lines.append("Solver & Success (\\%) & Mean Time (s) & Median Time (s) & Wins \\\\")
lines.append("\\midrule")
h_succ = rate(results, 'highs_success')
c_succ = rate(results, 'cbc_success')
h_mean = mtime(results, 'highs_time')
c_mean = mtime(results, 'cbc_time')
h_med = float(np.median([r['highs_time'] for r in results]))
c_med = float(np.median([r['cbc_time'] for r in results]))
h_wins = sum(1 for r in results if r['highs_time'] < r['cbc_time'] and r['highs_success'])
c_wins = sum(1 for r in results if r['cbc_time'] < r['highs_time'] and r['cbc_success'])
lines.append(f"HiGHS & {h_succ:.1f} & {h_mean:.3f} & {h_med:.3f} & {h_wins}/{len(results)} \\\\")
lines.append(f"CBC   & {c_succ:.1f} & {c_mean:.3f} & {c_med:.3f} & {c_wins}/{len(results)} \\\\")
lines.append("\\bottomrule")
lines.append("\\end{tabular}")
lines.append("\\end{table}\n")

# ============================================================
# TABLE 3: Success by secret type at max dimension
# ============================================================
max_n = max(dims)
lines.append(f"% === TABLE 3: Success Rate by Secret Type (n={max_n}) ===")
lines.append("\\begin{table}[t]")
lines.append(f"\\caption{{Success rate (\\%) by secret distribution at $n={max_n}$ ($q={q}$, $m={2*max_n}$).}}")
lines.append("\\label{tab:success-secret}")
lines.append("\\centering")
lines.append("\\small")
lines.append("\\begin{tabular}{lcccc}")
lines.append("\\toprule")
lines.append("Secret Type & MILP-HiGHS & MILP-CBC & LLL & BKZ-15 \\\\")
lines.append("\\midrule")
for sec in sec_types:
    sub = [r for r in results if r['n'] == max_n and r['secret_type'] == sec]
    h = rate(sub, 'highs_success')
    c = rate(sub, 'cbc_success')
    l = rate(sub, 'lll_success')
    b = rate(sub, 'bkz_success')
    best = max(h, c, l, b)
    def bf(v):
        return f"\\textbf{{{v:.1f}}}" if abs(v - best) < 0.5 else f"{v:.1f}"
    lines.append(f"{sec.capitalize()} & {bf(h)} & {bf(c)} & {bf(l)} & {bf(b)} \\\\")
lines.append("\\bottomrule")
lines.append("\\end{tabular}")
lines.append("\\end{table}\n")

# ============================================================
# TABLE 4: Mean time by dimension and method
# ============================================================
lines.append("% === TABLE 4: Mean Time-to-Solution by Dimension ===")
lines.append("\\begin{table}[t]")
lines.append("\\caption{Mean time-to-solution (seconds) by dimension, averaged over all secret types and instances.}")
lines.append("\\label{tab:time-dim}")
lines.append("\\centering")
lines.append("\\small")
lines.append("\\begin{tabular}{ccccc}")
lines.append("\\toprule")
lines.append("$n$ & MILP-HiGHS & MILP-CBC & LLL & BKZ-15 \\\\")
lines.append("\\midrule")
for n in dims:
    sub = [r for r in results if r['n'] == n]
    h = mtime(sub, 'highs_time')
    c = mtime(sub, 'cbc_time')
    l = mtime(sub, 'lll_time')
    b = mtime(sub, 'bkz_time')
    lines.append(f"{n} & {h:.3f} & {c:.3f} & {l:.3f} & {b:.3f} \\\\")
lines.append("\\bottomrule")
lines.append("\\end{tabular}")
lines.append("\\end{table}\n")

# ============================================================
# KEY STATS for the paper
# ============================================================
lines.append("% === KEY STATISTICS FOR PAPER ===")
lines.append(f"% HiGHS mean time over all runs: {h_mean:.4f} s")
lines.append(f"% CBC mean time over all runs:   {c_mean:.4f} s")
lines.append(f"% HiGHS speedup over CBC:        {c_mean/h_mean:.2f}x")
lines.append(f"% HiGHS total success rate:      {h_succ:.2f}%")
lines.append(f"% CBC total success rate:        {c_succ:.2f}%")
lines.append(f"% HiGHS wins (faster + solved):  {h_wins}/{len(results)}")
lines.append(f"% CBC wins (faster + solved):    {c_wins}/{len(results)}")
lines.append(f"% Total instances:               {len(results)}")

with open(OUT_FILE, 'w') as f:
    f.write('\n'.join(lines))

print(f"LaTeX tables saved to {OUT_FILE}")
print(f"\nKey stats:")
print(f"  HiGHS mean time: {h_mean:.4f}s  |  CBC mean time: {c_mean:.4f}s  |  Speedup: {c_mean/h_mean:.2f}x")
print(f"  HiGHS success: {h_succ:.1f}%  |  CBC success: {c_succ:.1f}%")
print(f"  HiGHS faster: {h_wins}/{len(results)}  |  CBC faster: {c_wins}/{len(results)}")